### ISSUE TITLE
Question about returning multiple users.

### ISSUE THREAD

**Issue by josephdburdick** [eventedmind/class-build-a-multi-page-app-with-iron-meteor-6737880d#1]
If you're developing this app locally and the only way to login is by using your meteor-developer account how are you returning more than 1 user?

**Comment by josephdburdick** [comment]
Nevermind, I ended up using 
```
if (Meteor.users.find().count() === 1) { Accounts.createUser({ ...
``` 
In bootstrap.js to create a dummy user. I could have also just created another meteor-developer account.

**Comment by cmather** [comment]
Hi @josephdburdick, glad you came up with a way to do it. The way I achieved this in the video is that I have two meteor account users. I logged in using the other account. A quick way to do this without logging out of your other session is to open a new browser window in anonymous mode (command + shift + N on a mac). This will bring up a new browser with the local storage and session cleared. You can then log in with a different user. Of course, the user must exist in the meteor account system.

**Comment by josephdburdick** [comment]
@cmather Thanks for explaining that. I'd mention that next time for dense individuals such as myself :sleeping:. Great videos, this is actually the 3rd month I've paid to subscribe to your videos.

**Comment by cmather** [comment]
Thanks for subscribing Joe. And stay tuned for new stuff coming soon.
